"""Rigorous interval arithmetic for Python.

pyintval implements IEEE 1788-2015 set-based interval arithmetic with
correctly rounded double-precision endpoints: every operation returns an
interval mathematically guaranteed to contain the true result.

Example
-------
>>> import pyintval as iv
>>> x = iv.Interval("0.1")          # rigorously encloses the decimal 0.1
>>> y = iv.sqrt(x) + iv.Interval(2) * x
>>> y.lo <= y.hi
True
>>> iv.Interval(1) / iv.Interval(-1, 1)   # division straddling zero
Interval('[entire]')
"""

from __future__ import annotations

from pyintval._core import (
    KERNEL_ABI_VERSION,
    DecoratedInterval,
    Interval,
    __version__,
    abs,
    abs_rev,
    acos,
    acosh,
    asin,
    asinh,
    atan,
    atan2,
    atanh,
    build_info,
    cancel_minus,
    cancel_plus,
    cbrt,
    ceil,
    cos,
    cosh,
    e,
    empty,
    entire,
    erf,
    erfc,
    exp,
    exp2,
    exp10,
    expm1,
    floor,
    fma,
    hull,
    hypot,
    intersection,
    log,
    log1p,
    log2,
    log10,
    max,
    min,
    mul_rev,
    pi,
    pow,
    pown,
    recip,
    round,
    round_ties_to_away,
    sign,
    sin,
    sinh,
    sqr,
    sqr_rev,
    sqrt,
    tan,
    tanh,
    trunc,
)

__all__ = [
    "KERNEL_ABI_VERSION",
    "DecoratedInterval",
    "Interval",
    "__version__",
    "abs",
    "abs_rev",
    "acos",
    "acosh",
    "asin",
    "asinh",
    "atan",
    "atan2",
    "atanh",
    "build_info",
    "cancel_minus",
    "cancel_plus",
    "cbrt",
    "ceil",
    "cos",
    "cosh",
    "e",
    "empty",
    "entire",
    "erf",
    "erfc",
    "exp",
    "exp2",
    "exp10",
    "expm1",
    "floor",
    "fma",
    "hull",
    "hypot",
    "intersection",
    "log",
    "log1p",
    "log2",
    "log10",
    "max",
    "min",
    "mul_rev",
    "pi",
    "pow",
    "pown",
    "recip",
    "round",
    "round_ties_to_away",
    "sign",
    "sin",
    "sinh",
    "sqr",
    "sqr_rev",
    "sqrt",
    "tan",
    "tanh",
    "trunc",
]
