"""Type stubs for the compiled pyintval._core module."""

from typing import Any

__version__: str
KERNEL_ABI_VERSION: int

def build_info() -> dict[str, Any]: ...

Scalar = "Interval | float | int"

class Interval:
    def __init__(self, lo: Interval | float | int | str, hi: float | int | None = ...) -> None: ...
    @staticmethod
    def empty() -> Interval: ...
    @staticmethod
    def entire() -> Interval: ...
    @property
    def lo(self) -> float: ...
    @property
    def hi(self) -> float: ...
    @property
    def mid(self) -> float: ...
    @property
    def rad(self) -> float: ...
    @property
    def wid(self) -> float: ...
    @property
    def mag(self) -> float: ...
    @property
    def mig(self) -> float: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def is_entire(self) -> bool: ...
    @property
    def is_singleton(self) -> bool: ...
    @property
    def is_common(self) -> bool: ...
    @property
    def endpoints(self) -> tuple[float, float]: ...
    def __add__(self, other: Interval | float | int) -> Interval: ...
    def __radd__(self, other: Interval | float | int) -> Interval: ...
    def __sub__(self, other: Interval | float | int) -> Interval: ...
    def __rsub__(self, other: Interval | float | int) -> Interval: ...
    def __mul__(self, other: Interval | float | int) -> Interval: ...
    def __rmul__(self, other: Interval | float | int) -> Interval: ...
    def __truediv__(self, other: Interval | float | int) -> Interval: ...
    def __rtruediv__(self, other: Interval | float | int) -> Interval: ...
    def __neg__(self) -> Interval: ...
    def __pos__(self) -> Interval: ...
    def __abs__(self) -> Interval: ...
    def __pow__(self, exponent: int | float, modulo: None = ...) -> Interval: ...
    def __and__(self, other: Interval) -> Interval: ...
    def __or__(self, other: Interval) -> Interval: ...
    def intersection(self, other: Interval) -> Interval: ...
    def hull(self, other: Interval) -> Interval: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __contains__(self, item: Interval | float | int) -> bool: ...
    def __hash__(self) -> int: ...
    def subset(self, other: Interval) -> bool: ...
    def superset(self, other: Interval) -> bool: ...
    def is_interior_to(self, other: Interval) -> bool: ...
    def is_disjoint(self, other: Interval) -> bool: ...
    def overlaps(self, other: Interval) -> bool: ...
    def contains(self, value: Interval | float | int) -> bool: ...
    def precedes(self, other: Interval) -> bool: ...
    def strict_precedes(self, other: Interval) -> bool: ...
    def less(self, other: Interval) -> bool: ...
    def strict_less(self, other: Interval) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __copy__(self) -> Interval: ...
    def __deepcopy__(self, memo: dict) -> Interval: ...

def empty() -> Interval: ...
def entire() -> Interval: ...
def sqrt(x: Interval) -> Interval: ...
def sqr(x: Interval) -> Interval: ...
def abs(x: Interval) -> Interval: ...
def recip(x: Interval) -> Interval: ...
def fma(x: Interval, y: Interval, z: Interval) -> Interval: ...
def pown(x: Interval, n: int) -> Interval: ...
def floor(x: Interval) -> Interval: ...
def ceil(x: Interval) -> Interval: ...
def trunc(x: Interval) -> Interval: ...
def round(x: Interval) -> Interval: ...
def round_ties_to_away(x: Interval) -> Interval: ...
def sign(x: Interval) -> Interval: ...
def min(x: Interval, y: Interval) -> Interval: ...
def max(x: Interval, y: Interval) -> Interval: ...
def hull(x: Interval, y: Interval) -> Interval: ...
def intersection(x: Interval, y: Interval) -> Interval: ...
def cancel_minus(a: Interval, b: Interval) -> Interval: ...
def cancel_plus(a: Interval, b: Interval) -> Interval: ...
def mul_rev(b: Interval, c: Interval, x: Interval = ...) -> Interval: ...
def sqr_rev(c: Interval, x: Interval = ...) -> Interval: ...
def abs_rev(c: Interval, x: Interval = ...) -> Interval: ...
def exp(x: Interval) -> Interval: ...
def exp2(x: Interval) -> Interval: ...
def exp10(x: Interval) -> Interval: ...
def expm1(x: Interval) -> Interval: ...
def log(x: Interval) -> Interval: ...
def log2(x: Interval) -> Interval: ...
def log10(x: Interval) -> Interval: ...
def log1p(x: Interval) -> Interval: ...
def cbrt(x: Interval) -> Interval: ...
def sin(x: Interval) -> Interval: ...
def cos(x: Interval) -> Interval: ...
def tan(x: Interval) -> Interval: ...
def asin(x: Interval) -> Interval: ...
def acos(x: Interval) -> Interval: ...
def atan(x: Interval) -> Interval: ...
def atan2(y: Interval, x: Interval) -> Interval: ...
def sinh(x: Interval) -> Interval: ...
def cosh(x: Interval) -> Interval: ...
def tanh(x: Interval) -> Interval: ...
def asinh(x: Interval) -> Interval: ...
def acosh(x: Interval) -> Interval: ...
def atanh(x: Interval) -> Interval: ...
def hypot(x: Interval, y: Interval) -> Interval: ...
def pow(x: Interval, y: Interval) -> Interval: ...
def erf(x: Interval) -> Interval: ...
def erfc(x: Interval) -> Interval: ...
def pi() -> Interval: ...
def e() -> Interval: ...
